// <auto-generated />
using System;
using ComputeFutureValue.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputeFutureValue.Api.Migrations
{
    [DbContext(typeof(ComputeFutureValueDbContext))]
    partial class ComputeFutureValueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ComputeFutureValue.Common.Entities.InvoiceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("FutureValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IncrementalRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LowerBoundInterestRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Maturity")
                        .HasColumnType("int");

                    b.Property<decimal>("PresentValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("UpperBoundInterestRate")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("ComputeFutureValue.Common.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("InvoiceHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceHistoryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComputeFutureValue.Common.Entities.User", b =>
                {
                    b.HasOne("ComputeFutureValue.Common.Entities.InvoiceHistory", "InvoiceHistory")
                        .WithMany()
                        .HasForeignKey("InvoiceHistoryId");

                    b.Navigation("InvoiceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
